apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aap-min-side-microfrontend
  namespace: aap
  labels:
    team: aap
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-min-side
          namespace: min-side
    outbound:
      rules:
        - application: innsending
  env:
  - name: INNSENDING_API_URL
    value: "http://innsending"
  - name: MINE_AAP_URL
    value: "https://www.nav.no/aap/mine-aap/"
  image: {{ image }}
  port: 8080
  liveness:
    path: /api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
