apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aap-min-side-microfrontend
  namespace: aap
  labels:
    team: aap
spec:
  env:
  - name: CORS_ALLOWED_ORIGIN
    value: "https://www.dev.nav.no"
  envFrom:
    - secret: aap-min-side-microfrontend-secrets
  image: {{ image }}
  port: 8080
  liveness:
    path: /aap-min-side-microfrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /aap-min-side-microfrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /aap-min-side-microfrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.dev.nav.no/aap/aap-min-side-microfrontend"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
