name: "Build and deploy"
on:
  push:
    branches:
      - "main"
      - "dev-*"
  workflow_dispatch:

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
      - name: "Install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: "Run tests"
        run: "npm run test"

      - name: "Build application"
        run: "npm run build"

      - name: "Rename manifest if dev"
        if: github.ref != 'refs/heads/main'
        run: "mv dist/manifest.json dist/dev-manifest.json"

      - name: cdn-upload
        uses: navikt/frontend/actions/cdn-upload/v1@main
        with:
          cdn-team-name: aap
          source: ./dist/
          destination: "aap-min-side-microfrontend"

  trigger_manifest_update_dev:
    if: github.ref != 'refs/heads/main'
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    with:
      cluster: "dev-gcp"
      id: "aap"
      url: "https://cdn.nav.no/aap/aap-min-side-microfrontend/dist/dev-manifest.json"
    secrets: inherit
  trigger_manifest_update_prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest.yaml@main
    with:
      cluster: "prod-gcp"
      id: "aap"
      url: "https://cdn.nav.no/aap/aap-min-side-microfrontend/dist/manifest.json"
    secrets: inherit
